### ISSUE TITLE
Visual Studio 2017 availability

### ISSUE THREAD

**Issue by lvmajor** [reduckted/SelectHyphenated#1]
Any plan to make it available for Visual Studio 2017?

**Comment by reduckted** [comment]
Definitely! I've made the changes and it works in Visual Studio 2017, but the upgraded VSIX doesn't work in 2015 (even though it installs fine). 😢 Once I get that worked out, I'll publish the updated version.

**Comment by reduckted** [comment]
Well that was easier to fix than I thought. I'd upgraded _all_ of the NuGet packages. Turns out I should have only updated the build tools package and left the rest of them at v14.

The new extension is now published.

**Comment by lvmajor** [comment]
Nice! Thanks for taking the time to update it. I really like  this extension 😉 Also happy you could find your problem with the VS2015 version!
